export const sampleData = {
  students: [
    {
      id: "S001",
      firstName: "Emma",
      lastName: "Johnson",
      gender: "Female",
      parentEmail1: "parent1@example.com",
      parentEmail2: "parent2@example.com",
      phone: "555-123-4567",
      medicalNotes: "Mild peanut allergy",
    },
    {
      id: "S002",
      firstName: "Liam",
      lastName: "Smith",
      gender: "Male",
      parentEmail1: "parent3@example.com",
      parentEmail2: "",
      phone: "555-234-5678",
      medicalNotes: "",
    },
    {
      id: "S003",
      firstName: "Olivia",
      lastName: "Davis",
      gender: "Female",
      parentEmail1: "parent4@example.com",
      parentEmail2: "",
      phone: "555-345-6789",
      medicalNotes: "Asthma",
    },
    {
      id: "S004",
      firstName: "Noah",
      lastName: "Miller",
      gender: "Male",
      parentEmail1: "parent5@example.com",
      parentEmail2: "parent6@example.com",
      phone: "555-456-7890",
      medicalNotes: "",
    },
    {
      id: "S005",
      firstName: "Ava",
      lastName: "Wilson",
      gender: "Female",
      parentEmail1: "parent7@example.com",
      parentEmail2: "",
      phone: "555-567-8901",
      medicalNotes: "",
    },
    {
      id: "S006",
      firstName: "Elijah",
      lastName: "Moore",
      gender: "Male",
      parentEmail1: "parent8@example.com",
      parentEmail2: "",
      phone: "555-678-9012",
      medicalNotes: "",
    },
    {
      id: "S007",
      firstName: "Sophia",
      lastName: "Taylor",
      gender: "Female",
      parentEmail1: "parent9@example.com",
      parentEmail2: "parent10@example.com",
      phone: "555-789-0123",
      medicalNotes: "",
    },
    {
      id: "S008",
      firstName: "James",
      lastName: "Anderson",
      gender: "Male",
      parentEmail1: "parent11@example.com",
      parentEmail2: "",
      phone: "555-890-1234",
      medicalNotes: "Lactose intolerant",
    },
    {
      id: "S009",
      firstName: "Isabella",
      lastName: "Thomas",
      gender: "Female",
      parentEmail1: "parent12@example.com",
      parentEmail2: "",
      phone: "555-901-2345",
      medicalNotes: "",
    },
    {
      id: "S010",
      firstName: "Benjamin",
      lastName: "Jackson",
      gender: "Male",
      parentEmail1: "parent13@example.com",
      parentEmail2: "parent14@example.com",
      phone: "555-012-3456",
      medicalNotes: "",
    },
    {
      id: "S011",
      firstName: "Mia",
      lastName: "White",
      gender: "Female",
      parentEmail1: "parent15@example.com",
      parentEmail2: "",
      phone: "555-112-3344",
      medicalNotes: "",
    },
    {
      id: "S012",
      firstName: "Alex",
      lastName: "Rivera",
      gender: "Other",
      parentEmail1: "parent16@example.com",
      parentEmail2: "",
      phone: "555-223-4455",
      medicalNotes: "",
    },
    {
      id: "S013",
      firstName: "Lucas",
      lastName: "Harris",
      gender: "Male",
      parentEmail1: "parent16@example.com",
      parentEmail2: "",
      phone: "555-223-4455",
      medicalNotes: "",
    },
    {
      id: "S014",
      firstName: "Charlotte",
      lastName: "Martin",
      gender: "Female",
      parentEmail1: "parent17@example.com",
      parentEmail2: "parent18@example.com",
      phone: "555-334-5566",
      medicalNotes: "",
    },
    {
      id: "S015",
      firstName: "Henry",
      lastName: "Thompson",
      gender: "Male",
      parentEmail1: "parent19@example.com",
      parentEmail2: "",
      phone: "555-445-6677",
      medicalNotes: "",
    },
    {
      id: "S016",
      firstName: "Amelia",
      lastName: "Garcia",
      gender: "Female",
      parentEmail1: "parent20@example.com",
      parentEmail2: "",
      phone: "555-556-7788",
      medicalNotes: "Gluten sensitivity",
    },
    {
      id: "S017",
      firstName: "Jordan",
      lastName: "Lee",
      gender: "Prefer not to say",
      parentEmail1: "parent21@example.com",
      parentEmail2: "",
      phone: "555-667-8899",
      medicalNotes: "",
    },
  ],
  englishGrades: [
    {
      studentId: "S001",
      assignmentId: "E001",
      assignmentName: "Vocabulary Quiz 1",
      category: "Quiz",
      points: 20,
      score: 18,
      dateEntered: "2025-09-10",
      subject: "English",
    },
    {
      studentId: "S001",
      assignmentId: "E002",
      assignmentName: "Book Report",
      category: "Essay",
      points: 50,
      score: 45,
      dateEntered: "2025-09-15",
      subject: "English",
    },
    {
      studentId: "S002",
      assignmentId: "E001",
      assignmentName: "Vocabulary Quiz 1",
      category: "Quiz",
      points: 20,
      score: 15,
      dateEntered: "2025-09-10",
      subject: "English",
    },
    {
      studentId: "S002",
      assignmentId: "E002",
      assignmentName: "Book Report",
      category: "Essay",
      points: 50,
      score: 40,
      dateEntered: "2025-09-15",
      subject: "English",
    },
    {
      studentId: "S003",
      assignmentId: "E001",
      assignmentName: "Vocabulary Quiz 1",
      category: "Quiz",
      points: 20,
      score: 19,
      dateEntered: "2025-09-10",
      subject: "English",
    },
    {
      studentId: "S003",
      assignmentId: "E002",
      assignmentName: "Book Report",
      category: "Essay",
      points: 50,
      score: 48,
      dateEntered: "2025-09-15",
      subject: "English",
    },
  ],
  socialStudiesGrades: [
    {
      studentId: "S001",
      assignmentId: "SS001",
      assignmentName: "States and Capitals Quiz",
      category: "Quiz",
      points: 25,
      score: 22,
      dateEntered: "2025-09-12",
      subject: "Social Studies",
    },
    {
      studentId: "S001",
      assignmentId: "SS002",
      assignmentName: "History Timeline Project",
      category: "Project",
      points: 100,
      score: 90,
      dateEntered: "2025-09-20",
      subject: "Social Studies",
    },
    {
      studentId: "S002",
      assignmentId: "SS001",
      assignmentName: "States and Capitals Quiz",
      category: "Quiz",
      points: 25,
      score: 20,
      dateEntered: "2025-09-12",
      subject: "Social Studies",
    },
    {
      studentId: "S002",
      assignmentId: "SS002",
      assignmentName: "History Timeline Project",
      category: "Project",
      points: 100,
      score: 85,
      dateEntered: "2025-09-20",
      subject: "Social Studies",
    },
    {
      studentId: "S003",
      assignmentId: "SS001",
      assignmentName: "States and Capitals Quiz",
      category: "Quiz",
      points: 25,
      score: 24,
      dateEntered: "2025-09-12",
      subject: "Social Studies",
    },
    {
      studentId: "S003",
      assignmentId: "SS002",
      assignmentName: "History Timeline Project",
      category: "Project",
      points: 100,
      score: 95,
      dateEntered: "2025-09-20",
      subject: "Social Studies",
    },
  ],
  assignments: [
    {
      id: "E001",
      subject: "English",
      name: "Vocabulary Quiz 1",
      category: "Quiz",
      points: 20,
      dueDate: "2025-09-09",
      description: "Quiz covering vocabulary words from Unit 1",
    },
    {
      id: "E002",
      subject: "English",
      name: "Book Report",
      category: "Essay",
      points: 50,
      dueDate: "2025-09-14",
      description: "1-2 page report on the assigned reading book",
    },
    {
      id: "SS001",
      subject: "Social Studies",
      name: "States and Capitals Quiz",
      category: "Quiz",
      points: 25,
      dueDate: "2025-09-11",
      description: "Quiz on the first 25 states and their capitals",
    },
    {
      id: "SS002",
      subject: "Social Studies",
      name: "History Timeline Project",
      category: "Project",
      points: 100,
      dueDate: "2025-09-19",
      description: "Research and create a timeline of historical events",
    },
  ],
  attendance: [
    {
      studentId: "S001",
      date: "2025-09-01",
      status: "Present",
      notes: "",
      timeEntered: "08:15:00",
    },
    {
      studentId: "S002",
      date: "2025-09-01",
      status: "Absent",
      notes: "Parent called - doctor appointment",
      timeEntered: "08:15:00",
    },
    {
      studentId: "S003",
      date: "2025-09-01",
      status: "Present",
      notes: "",
      timeEntered: "08:15:00",
    },
  ],
  behavior: [
    {
      studentId: "S001",
      date: "2025-09-05",
      type: "Positive",
      description: "Helped another student with classwork",
      severity: "Low",
      actionTaken: "Verbal praise",
    },
    {
      studentId: "S003",
      date: "2025-09-07",
      type: "Negative",
      description: "Talking during quiet reading time",
      severity: "Low",
      actionTaken: "Verbal warning",
    },
  ],
  communications: [
    {
      studentId: "S001",
      date: "2025-09-08",
      type: "Email",
      subject: "Weekly Progress Update",
      content:
        "Emma is doing well in both subjects. She scored 90% on her recent vocabulary quiz.",
      sentStatus: "Sent",
    },
    {
      studentId: "S002",
      date: "2025-09-08",
      type: "Email",
      subject: "Absence Follow-up",
      content:
        "Just following up on Liam's absence yesterday. Please let me know if he needs any makeup work.",
      sentStatus: "Draft",
    },
  ],
  settings: [
    {
      name: "GradeScale",
      value: "A:90-100,B:80-89,C:70-79,D:60-69,F:0-59",
    },
    {
      name: "EnglishWeights",
      value: "Tests:40,Quizzes:20,Essays:25,Participation:15",
    },
    {
      name: "SocialStudiesWeights",
      value: "Tests:35,Quizzes:15,Projects:30,Homework:20",
    },
    {
      name: "DailyEmailTime",
      value: "17:00",
    },
    {
      name: "WeeklyEmailDay",
      value: "Friday",
    },
  ],
};

export default sampleData;
